### ISSUE TITLE
Making the workflows more efficient.

### ISSUE THREAD

**Issue by adityasimant** [mrbusche/random-website-checker#1157]
We can make the current workflows more efficient by :
1. Using a matrix strategy for JDK versions: Instead of setting up a specific JDK version, we can use a matrix strategy to test our code against multiple JDK versions.
2. Cache Gradle dependencies: To speed up build times, you can cache Gradle dependencies so that they don't need to be re-downloaded every time.

**Comment by mrbusche** [comment]
Sounds good to me!

**Comment by mrbusche** [comment]
Resolved with https://github.com/mrbusche/random-website-checker/pull/1159
